@echo on
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause  -notga -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_test_hdrup.pfm"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_testup.tga"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause  -notga -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_test_hdrdn.pfm"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_testdn.tga"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause  -notga -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_test_hdrrt.pfm"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_testrt.tga"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause  -notga -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_test_hdrlf.pfm"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_testlf.tga"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause  -notga -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_test_hdrbk.pfm"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_testbk.tga"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause  -notga -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_test_hdrft.pfm"
"D:\Steam Games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\vtex.exe" -game "D:\Steam Games\steamapps\sourcemods\GillespiePass" -nopause -mkdir "D:\Steam Games\steamapps\sourcemods\GillespiePass\materialsrc\skybox\sky_testft.tga"
@pause
